### ISSUE TITLE
As a Restaurant owner/chef, I can notify the customer that their order is ready for pick-up.

### ISSUE THREAD

**Issue by JamesSoaresCorreia** [comp231-S4G3/DineOut#35]
- [x] #30 Research   about email API
- [x] #31 Implement   email API
- [x] #32 Create Email template

**Comment by JamesSoaresCorreia** [comment]
### Acceptance Tests

Test sending notification by clicking ready 

**Expected outcome:** an email should be sent to the customer that the order belongs to, notifying them that their food is ready to be picked up.
