### ISSUE TITLE
As a restaurant owner/chef, I can view individual order details and see the status of that order

### ISSUE THREAD

**Issue by JamesSoaresCorreia** [comp231-S4G3/DineOut#36]
- [x] #27 Create Order Details view (owner side)
- [x] #28 Create Order Details   controller
- [x] #29 Add update order status functionality

**Comment by JamesSoaresCorreia** [comment]
### Acceptance Tests

Test viewing an incomplete order 
**Expected outcome:** owner/chef should see the details of the selected order and see that it has an incomplete status. 


Test viewing a completed order 
**Expected outcome:** owner/chef should see the details of the selected order and see that it has a complete status. 

 
Test viewing an order by clicking on the order 
**Expected outcome:** owner/chef should be redirected to the order details page showing that order’s details including: order ID, customer ID, date and time of order, order items and their quantity
