### ISSUE TITLE
 As a restaurant owner/chef, I can view a list of my current and completed orders.

### ISSUE THREAD

**Issue by JamesSoaresCorreia** [comp231-S4G3/DineOut#37]
- [x] #25 Create an order list view
- [x] #26 Create search functionality
- [x] #67 Create order filter

**Comment by JamesSoaresCorreia** [comment]
### Acceptance tests

Test viewing list of current orders by clicking orders 

**Expected outcome:** should return a list of all orders  

 

Test searching list of completed orders: 

**Expected outcome:** should return a list of orders that match the search query 

 

Test order filter by status by filtering to orders whose status are complete 

**Expected outcome:** a list of order whose status is ‘complete’ is returned
