### ISSUE TITLE
As a customer, I can add, remove items to my order as well as add custom notes

### ISSUE THREAD

**Issue by JamesSoaresCorreia** [comp231-S4G3/DineOut#39]
- [x] #20 Create Order Model
- [x] #21 Create Order View
- [x] #22 Order Crud Functionality
- [x] #23 Create Order Controller

**Comment by JamesSoaresCorreia** [comment]
### Acceptance Tests

Test adding an item to an order. View order summary 

**Expected outcome:** an item should be added to current order. 
 

Test removing items from an order. View order summary 

**Expected outcome:** item should be removed from a current order 


Test adding custom notes to an order. Confirm the order 
**Expected outcome:** custom notes should be saved to current order. when looking at the order, the custom notes will be seen.
