### ISSUE TITLE
As a restaurant owner, I can access my restaurant page so that I can modify or build a menu, generate a QR code for the restaurant.

### ISSUE THREAD

**Issue by JamesSoaresCorreia** [comp231-S4G3/DineOut#41]
- [x] #15 Create Restaurant view
- [x] #16 Create Restaurant controller
- [x] #17 Create Restaurant Model

**Comment by JamesSoaresCorreia** [comment]
### Acceptance tests

Test that restaurant page is accessible 

**Expected outcome:** owner should be able to access restaurant page when signed in 



Test that from the restaurant page, the owner can click Menu 

**Expected outcome:** owner should be directed from his restaurant page to his restaurant’s menu 

 

Test that from the restaurant page, an owner can click on Orders 

**Expected outcome:** owner should be directed from his restaurant page to the Order List view. 

 

Test that an owner can click on QR code 

**Expected outcome:** redirects to an image of the Restaurant’s QR code
