### ISSUE TITLE
As a restaurant owner, I can add/delete items to the menu, mark items availability and edit item details.

### ISSUE THREAD

**Issue by JamesSoaresCorreia** [comp231-S4G3/DineOut#43]
- [x] #6  Create model for menu
- [x] #7  Add CRUD functionality to menu 
- [x] #8 Create initial system database
- [x] #9 Create Menu View
- [x] #10 Item Model
- [x] #11 Create item view
- [x] #12 Create Menu Action

**Comment by JamesSoaresCorreia** [comment]
### Acceptance tests:

Test that item includes information for details, price, ingredients, availability, a picture. 

**Expected outcome:** the item includes details, ingredients, price, availability and picture. 


Test adding an item to a menu. Click the add item button, fill in the item details and save the item. 

**Expected outcome:** Item should be added to restaurant’s menu. 


Test removing an item from the menu. Remove an item by clicking delete, a confirmation dialogue should ask the user if they are sure they want the item deleted. 

**Expected outcome:** Item should be removed from restaurant’s menu. 


Test editing item details. Click on edit item button. Change item name, ingredients, description  

and click save. 

**Expected outcome:** The changes made should now be saved and reflected in the item. 


Test marking an item out of stock. Click an item, set availability to out of stock. 

**Expected outcome:** Item should be greyed out on menu and unorderable 


Test marking an item back in stock. Click an item, set availability to in stock. 

**Expected outcome:** Item should not be greyed out anymore and should be orderable again
